name: chm

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initial run
        env:
          GH_TOKEN_SELF: ${{ secrets.GH_TOKEN_SELF }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # CT: ${{ secrets.CT_2 }}
          CT: ${{ secrets.CT }}
        run: |
          git clone https://${GH_TOKEN_SELF}@github.com/no286155/yumeanime.git
          mv yumeanime/chatbot-hm.sh .
          chmod +x chatbot-hm.sh
          ./chatbot-hm.sh "$CT" "$GH_TOKEN"
