name: OOO

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initial run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_SELF }}
          CT: ${{ secrets.CT_2 }}
        run: |
          git clone https://${GH_TOKEN}@github.com/no286155/yumeanime.git
          mv yumeanime/chatbot.sh .
          chmod +x chatbot.sh
          ./chatbot.sh "$CT"
